shoppingmall/urls.py
from django.contrib import admin
from django.urls import path,include


from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path


urlpatterns = [
    path('admin/', admin.site.urls),
    path('markdownx/', include('markdownx.urls')),
    path('',include('single_page.urls')),
    path('shoppingmall_main/',include('shoppingmall_main.urls')),
    path('accounts/', include('allauth.urls')),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shoppingmall_main/urls.py
from django.urls import path
from . import views

app_name = "shoppingitem"

urlpatterns = [

    path('',views.ShoppingItemList.as_view()),
    path('<int:pk>/',views.ShoppingItemDetail.as_view()),
    path('tag/<str:slug>/',views.tag_page),
    path('<int:pk>/new_comment/',views.new_comment),
    path('update_comment/<int:pk>/',views.CommentUpdate.as_view()),
    path('category/<str:slug>/',views.category_page),
    path('m_company/<str:slug>/',views.company_page),
    path('create_post/',views.ShoppingItemCreate.as_view()),
    path('update_post/<int:pk>/',views.ShoppingItemUpdate.as_view()),
    path('search/<str:q>/', views.ShoppingItemSearch.as_view()),
    path('delete_comment/<int:pk>/',views.delete_comment),
    path('<int:pk>/likes/', views.likes),
    path('recomment/<int:pk>/',views.recomment_create)


]

single_page/urls.py
from django.urls import path
from single_page import views

urlpatterns = [ #IP주소/
    path('',views.landing),
    path('about_me/',views.about_me),
    path('mypage/',views.mypage),
]

shoppingmall_main/models.py
from django.db import models
from django.contrib.auth.models import User
from markdownx.models import MarkdownxField
from markdownx.utils import markdown
from django import forms

import os
# Create your models here.


class Company(models.Model):
    name = models.CharField(max_length=30, unique=True) # 제조사명
    address = models.CharField(max_length=30) # 제조사 주소
    tel = models.CharField(max_length=15) # 제조사 연락처
    email = models.EmailField() # 제조사 이메일

    slug = models.SlugField(max_length=200, unique=True, allow_unicode=True,null=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return f'/shoppingmall_main/m_company/{self.slug}'

    class Meta:
        verbose_name_plural = 'Companies'

class Category(models.Model):
    name = models.CharField(max_length=50, unique=True)
    slug = models.SlugField(max_length=200, unique=True, allow_unicode=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return f'/shoppingmall_main/category/{self.slug}'

    class Meta:
        verbose_name_plural = 'Categories'

class ColorTag(models.Model):
    name = models.CharField(max_length=50,unique=True)
    slug = models.SlugField(max_length=200,unique=True,allow_unicode=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return f'/shoppingmall_main/tag/{self.slug}'

class ShoppingItem(models.Model):

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    title = models.CharField(max_length=50) # 상품 이름
    information = MarkdownxField() # 상품 설명
    price = models.IntegerField() # 가격
    like_users = models.ManyToManyField(User,related_name='like_shopping',blank=True)
    head_image = models.ImageField(upload_to='shoppingmall_main/images/%Y/%m/%d/', blank=True) # 상품 이미지
    author = models.ForeignKey(User, null=True, on_delete=models.SET_NULL)
    m_company = models.ForeignKey(Company, null=True, on_delete=models.SET_NULL) # 제조사
    category = models.ForeignKey(Category, null=True, blank=True, on_delete=models.CASCADE) # 카테고리
    product_number = models.IntegerField() # 그 외 상품번호
    tags = models.ManyToManyField(ColorTag,blank=True) # 다대다 관계

    def __str__(self):
        return f'{self.title} by {self.m_company}'

    def get_absolute_url(self):
        return f'/shoppingmall_main/{self.pk}/'
    def get_avatar_url(self):
        if self.author.socialaccount_set.exists():
            return self.author.socialaccount_set.first().get_avatar_url()
        else:
            return 'https://dummyimage.com/50x50/ced4da/6c757d.jpg'

    def get_content_markdown(self):
        return markdown(self.information)

class SubComment(models.Model):

    author = models.ForeignKey(User,on_delete=models.SET_NULL,null=True,related_name='subcomment')
    content = models.TextField(null=False)
    create_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.content


class Comment(models.Model):
    shoppingitem = models.ForeignKey(ShoppingItem, on_delete=models.CASCADE)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now = True)

    def __str__(self):
        return f'{self.author} : {self.content}'

    def get_absolute_url(self):
        return f'{self.shoppingitem.get_absolute_url()}#comment-{self.pk}'

    def get_avatar_url(self):
        if self.author.socialaccount_set.exists():
            return self.author.socialaccount_set.first().get_avatar_url()
        else:
            return 'https://dummyimage.com/50x50/ced4da/6c757d.jpg'

class ReComment(models.Model):
    post = models.ForeignKey(Comment, on_delete=models.CASCADE)
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    content = models.CharField(max_length=300)
    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.content

shoppingmall_main/forms.py
from .models import Comment,ReComment
from django import forms

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('content',)

class SubCommentForm(forms.ModelForm):
    class Meta:
        model = ReComment
        fields = ('content', )

shoppingmall_main/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from .models import ShoppingItem,Category,ColorTag,Comment,Company,ReComment
from django.views.generic import ListView, DetailView, CreateView, UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.core.exceptions import PermissionDenied
from django.utils.text import slugify
from .forms import CommentForm,SubCommentForm
from django.shortcuts import get_object_or_404
from django.db.models import Q
from django import forms

import os
# Create your views here.

class ShoppingItemList(ListView):
    model = ShoppingItem
    ordering = '-pk'
    paginate_by = 6

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(ShoppingItemList, self).get_context_data() ##템플릿에서 필요한 거 담아서 전달
        context['categories'] = Category.objects.all()
        context['no_category_post_count'] = ShoppingItem.objects.filter(category=None).count
        return context



class ShoppingItemDetail(DetailView):
    model = ShoppingItem

    def get_context_data(self, **kwargs):
        context = super(ShoppingItemDetail, self).get_context_data()
        context['categories'] = Category.objects.all()
        context['no_category_post_count'] = ShoppingItem.objects.filter(category=None).count
        context['comment_form'] = CommentForm
        context['subcomment_form'] = SubCommentForm
        return context

class ShoppingItemSearch(ShoppingItemList):
    paginate_by = None
    def get_queryset(self):
        q = self.kwargs['q']
        shoppingitem_list = ShoppingItem.objects.filter(
            Q(title__contains=q) | Q(tags__name__contains=q)
        ).distinct()

        return shoppingitem_list

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(ShoppingItemSearch,self).get_context_data()
        q = self.kwargs['q']
        context['search_info'] = f'Search : {q} ({self.get_queryset().count()})'
        return context



def category_page(request,slug):

    if slug=='no_category':
        category ='미분류'
        ShoppingItemList = ShoppingItem.objects.filter(category=None)
    else:
        category = Category.objects.get(slug=slug)
        ShoppingItemList =  ShoppingItem.objects.filter(category=category)

    return render(
        request,
        'shoppingmall_main/shoppingitem_list.html',{

            'category' :category,
            'shoppingitem_list' : ShoppingItemList,
            'categories': Category.objects.all(),
            'no_category_post_count': ShoppingItem.objects.filter(category=None).count(),
        }
    )

def company_page(request,slug):

    m_company = Company.objects.get(slug=slug)
    ShoppingItemList = ShoppingItem.objects.filter(m_company=m_company)

    return render(
        request,
        'shoppingmall_main/shoppingitem_list.html',{
            'company' :m_company,
            'shoppingitem_list' : ShoppingItemList,
            'companies': Company.objects.all(),
            'categories': Category.objects.all(),
            'no_category_post_count': ShoppingItem.objects.filter(category=None).count(),
        }
    )


def tag_page(request, slug):
    tag = ColorTag.objects.get(slug=slug)
    shoppingitem_list = tag.shoppingitem_set.all()

    return render(request, 'shoppingmall_main/shoppingitem_list.html', {
        'tag' : tag,
        'shoppingitem_list' : shoppingitem_list,
        'categories': Category.objects.all(),
        'no_category_post_count': ShoppingItem.objects.filter(category=None).count

    })

class ShoppingItemUpdate(UpdateView):
    model = ShoppingItem
    fields = ['title', 'information', 'price', 'head_image', 'm_company', 'category','product_number'] #,'tags'

    template_name = 'shoppingmall_main/shoppingitem_update_form.html'
    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated and request.user == self.get_object().author:
            return super(ShoppingItemUpdate, self).dispatch(request, *args, **kwargs)
        else:
            raise PermissionDenied

    def form_valid(self, form):
        response = super(ShoppingItemUpdate, self).form_valid(form)
        self.object.tags.clear()
        tags_str = self.request.POST.get('tags_str')
        if tags_str:
            tags_str = tags_str.strip()
            tags_str = tags_str.replace(',', ';')  # , -> ;로 바꿔준다
            tags_list = tags_str.split(';')  # ;를 기준으로 단어 나누기
            for t in tags_list:
                t = t.strip()
                tag, is_tag_created = ColorTag.objects.get_or_create(name=t)
                if is_tag_created:
                    tag.slug = slugify(t, allow_unicode=True)
                    tag.save()
                self.object.tags.add(tag)
        return response

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(ShoppingItemUpdate, self).get_context_data() ##템플릿에서 필요한 거 담아서 전달
        if self.object.tags.exists():
            tags_str_list = list() #빈 리스트 생성
            for t in self.object.tags.all():
                tags_str_list.append(t.name)
            context['tags_str_default'] = ';'.join(tags_str_list)
        context['categories'] = Category.objects.all()
        context['no_category_post_count'] = ShoppingItem.objects.filter(category=None).count
        return context

class ShoppingItemCreate(LoginRequiredMixin, UserPassesTestMixin, CreateView):
    model=ShoppingItem
    fields = ['title', 'information', 'price', 'head_image', 'm_company', 'category','product_number'] #, 'tags'

    def test_func(self):
        return self.request.user.is_superuser or self.request.user.is_staff

    def form_valid(self, form):
        current_user = self.request.user
        if current_user.is_authenticated and (current_user.is_superuser or current_user.is_staff):
            form.instance.author = current_user #form의 author값을 현재 로그인된 값으로 설정해줌
            response = super(ShoppingItemCreate,self).form_valid(form)
            tags_str = self.request.POST.get('tags_str')
            if tags_str :
                tags_str = tags_str.strip()
                tags_str = tags_str.replace(',',';') #, -> ;로 바꿔준다
                tags_list = tags_str.split(';') #;를 기준으로 단어 나누기
                for t in tags_list:
                    t = t.strip()
                    tag, is_tag_created = ColorTag.objects.get_or_create(name=t)
                    if is_tag_created:
                        tag.slug = slugify(t, allow_unicode=True)
                        tag.save()
                    self.object.tags.add(tag)
            return response
        else:
            return redirect('/shoppingmall_main/')

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(ShoppingItemCreate, self).get_context_data() ##템플릿에서 필요한 거 담아서 전달
        context['categories'] = Category.objects.all()
        context['no_category_post_count'] = ShoppingItem.objects.filter(category=None).count
        return context

def new_comment(request,pk):
    if request.user.is_authenticated:
        shoppingitem=get_object_or_404(ShoppingItem,pk=pk)
        if request.method == 'POST':
            comment_form = CommentForm(request.POST)
            if comment_form.is_valid():
                comment = comment_form.save(commit=False)
                comment.shoppingitem = shoppingitem
                comment.author = request.user
                comment.save()
                return redirect(comment.get_absolute_url())
            else:
                return redirect(shoppingitem.get_absolute_url())
        else:
            raise PermissionDenied

class CommentUpdate(LoginRequiredMixin,UpdateView):
    model = Comment
    form_class = CommentForm

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated and request.user == self.get_object().author:
            return super(CommentUpdate, self).dispatch(request, *args, **kwargs)
        else:
            raise PermissionDenied

def delete_comment(request,pk):
    comment = get_object_or_404(Comment,pk=pk)
    shoppingitem = comment.shoppingitem
    if request.user.is_authenticated and request.user == comment.author:
        comment.delete()
        return redirect(shoppingitem.get_absolute_url())
    else:
        raise PermissionDenied

def likes(request, pk):
    if request.user.is_authenticated:
        shoppingitem = get_object_or_404(ShoppingItem, pk=pk)

        if shoppingitem.like_users.filter(pk=request.user.pk).exists():
            shoppingitem.like_users.remove(request.user)
        else:
            shoppingitem.like_users.add(request.user)
        return redirect(request.META.get('HTTP_REFERER', 'redirect_if_referer_not_found'))
    raise  redirect(request.META.get('HTTP_REFERER', 'redirect_if_referer_not_found'))

from django.shortcuts import render, redirect
from django.views import View
from django.http import JsonResponse
import requests


class SubCommentForm(forms.ModelForm):
    class Meta:
        model = ReComment
        fields = ('content',)


def recomment_create(request,pk):
    if request.user.is_authenticated:

        form = SubCommentForm(request.POST)
        if form.is_valid():
            form = form.save(commit=False)
            form.post = get_object_or_404(Comment, pk=pk)
            form.user = request.user
            form.save()
    return redirect(form.post.get_absolute_url(), pk=form.post.shoppingitem.pk)

shoppingmall_main/templates/shoppingmall_main/base.html
<!DOCTYPE html>
{% load static %}
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block head_title %}Blog{% endblock %}</title>
    <link href="{% static 'shoppingmall_main/bootstrap4/css/bootstrap.min.css' %}" rel="stylesheet" media="screen">
    <link href="{% static 'shoppingmall_main/css/style.css' %}"   rel="stylesheet" media="screen" >
    <script src="https://kit.fontawesome.com/fc13d61e87.js" crossorigin="anonymous"></script>
</head>
<body>
    {% include 'shoppingmall_main/navbar.html' %}

    <div class="container">
      <div class="row">
        <div class="col-md-9 col-lg-10" id="main-area">
          {% block main_area %}
          {% endblock %}
        </div>
        <div class="col-md-3 col-lg-2">
            {% include 'shoppingmall_main/sidebar.html' %}
        </div>

      </div>

    </div>
{% include 'shoppingmall_main/footer.html' %}
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>
</body>
</html>

shoppingmall_main/templates/shoppingmall_main/comment_form.html
{% extends 'shoppingmall_main/base.html' %}
{% load crispy_forms_tags %}

{% block head_title %}
    Edit Comment - Blog
{% endblock %}

{% block main_area %}
<div class="container mt-3">
    <h1  style="color:rgb(0, 62, 62)">Edit Comment</h1>
    <hr>
    <form method="post" enctype="multipart/form-data" >
        {% csrf_token %}

            {{form | crispy}}

        <button type="submit" class="btn float-right m-3" style="background-color : snow; border: 2px solid rgb(0,62,62);border-radius:50%">Submit</button>
    </form>
</div>
{% endblock %}

shoppingmall_main/templates/shoppingmall_main/footer.html
<style>
    footer{
 background-color : rgb(0, 62, 62);
}

</style>
<footer class="py-3 mt-auto">
        <div class="container">
            <p class="m-0 display-9 text-center text-white"><small>Copyright &copy; HoLiday 2022</small></p>
            <p class="m-0 text-center text-white"><small>address : 서울특별시 도봉구 삼양로 144길 33</small></p>
            <p class="m-0 text-center text-white"><small>call : 010 5093 2019</small></p>
        </div>

</footer>

shoppingmall_main/templates/shoppingmall_main/shoppingitem_detail.html
{% extends 'shoppingmall_main/base.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block head_title %}
    {{shoppingitem.title}}
{% endblock %}
{% block main_area %}
<div class="container  mt-3">
                    <!-- Post content-->
                    <div id="post-area">
                        <!-- Post header-->
                        <header class="mb-4">
                            <!-- Post title-->
                            <span>
                                {% if user.is_authenticated and user == shoppingitem.author %}
                                <a href="/shoppingmall_main/update_post/{{shoppingitem.pk}}/" role="button" class="btn btn-sm float-right m-3" style="background-color : snow; border: 2px solid rgb(0,62,62);border-radius:50%" >
                                    Edit Post
                                </a>
                                {% endif %}
                            </span>
                            <h1 class="fw-bolder mb-1" style="color:rgb(0, 62, 62);">{{shoppingitem.title | lower}}</h1>


                            <!-- Post meta content-->
                            <div class="text-muted fst-italic mb-2">Posted on {{shoppingitem.created_at | date:"Y-m-d h:m:s"}} by {{shoppingitem.m_company | upper}}</div>
                            <!-- Post categories-->
                            {% if shoppingitem.category %}
                                <a class="badge  text-decoration-none"  style="background-color : rgb(0,62,62); border: 2px solid rgb(0,62,62); color:snow"href="{{shoppingitem.category.get_absolute_url}}">{{shoppingitem.category}}</a>
                            {% else %}
                                <a class="badge text-decoration-none " style="background-color:teal;color:white"  href="/shoppingmall_main/category/no_category/">미분류</a>
                            {% endif %}

                            <h5 class="mt-2 float-right">
                            {% if user.is_authenticated %}
                            {% if user in shoppingitem.like_users.all %}
                            <a href="/shoppingmall_main/{{shoppingitem.pk}}/likes"><i class="fa-solid fa-heart" style="color:red"></i></a>
                            {% else %}
                              <a href="/shoppingmall_main/{{shoppingitem.pk}}/likes"><i class="fa-solid fa-heart" style="color:black"></i></a>
                            {% endif %}
                            {% endif %}
                            <span>
                            {{shoppingitem.like_users.count}}명이 좋아합니다.</span></h5>

                        </header>

                        <!-- Preview image figure-->

                        <figure class="mb-4">
                            {% if shoppingitem.head_image %}
                            <img class="img-fluid rounded" src="{{shoppingitem.head_image.url}}" alt="{{p.title}}의 head_img" />
                            {% else %}
                            <img class="img-fluid rounded" src="https://picsum.photos/seed/{{shoppingitem.pk}}/800/200"/>
                            {% endif %}
                        </figure>


                        <!-- Post content-->
                        <section class="mb-5">
                            <p class="fs-5 mb-4">{{shoppingitem.get_content_markdown | safe }}</p>
                            {% if shoppingitem.tags.exists %}
                                <i class="fas fa-tag"></i>
                                {% for t in shoppingitem.tags.iterator %}
                                <span class="badge badge-light" style="color:rgb(0,62,62);background-color:snow;border:2px solid rgb(0,62,62)">
                                   <a href="{{t.get_absolute_url}}" style="color:rgb(0,62,62);">{{t}}</a>
                                </span>
                                {% endfor %}
                            {% endif %}

                        </section>


                    </div>
                    <!-- Comments section-->
                    <div id="comment-area" class="mb-5">
                        <div class="card " style="background-color:snow;border-radius:10px; color:rgb(0,62,62);">
                            <div class="card-body" >
                                <!-- Comment form-->
                                {% if user.is_authenticated %}
                                <form class="mb-4" id="comment-form" method="POST" style="background-color:snow;" action="{{shoppingitem.get_absolute_url}}new_comment/">
                                    {% csrf_token %}
                                    <div class="form-group" style="background-color:snow;" >
                                        {{ comment_form | crispy }}
                                    </div>
                                    <button type="submit" class="btn btn-light float-right" style="background-color : snow; border: 2px solid rgb(0,62,62);border-radius:50%">Submit</button>
                                    <br>
                                </form>
                                {% else %}
                                <a role="button" class="btn btn-light btn-block btn-sm m-2" style="color:rgb(0,62,62);"href="#" data-toggle="modal" data-target="#loginModal">
                                    Log in and leave a comment</a>
                                {% endif %}
                                {% if shoppingitem.comment_set.exists %}
                                {% for comment in shoppingitem.comment_set.iterator %}
                                <!-- Single comment-->
                                <div class="media d-flex id=comment-{{comment.pk}}">
                                    <img class="mr-3 rounded-circle" src="{{comment.get_avatar_url}}" alt="{{comment.author}}" width="60px"/>
                                    <div class="media-body ms-3">
                                        {% if user.is_authenticated and comment.author == user %}
                                        <div class="float-right">
                                            <a role="button" class="btn btn-sm btn-info" id="comment-{{ comment.pk }}-update-btn" href="/shoppingmall_main/update_comment/{{comment.pk}}/">Edit</a>
                                            <a role="button" class="btn btn-sm btn-danger" id="comment-{{ comment.pk }}-delete-modal-btn" href="#" data-toggle="modal" data-target="#deleteCommentModal-{{ comment.pk }}">Delete</a>
                                        </div>
                                        <!-- modal-->
                                        <div class="modal fade" id="deleteCommentModal-{{ comment.pk }}" tabindex="-1" role="dialog" aria-labelledby="deleteCommentModalLabel" aria-hidden="true">
                                            <div class="modal-dialog" role="document">
                                            <div class="modal-content">
                                                <div class="modal-header" style="color:black;">
                                                    <h5 class="modal-title" id="deleteModalLabel">Are you sure?</h5>
                                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                        <span aria-hidden="ture">&times;</span>
                                                    </button>
                                                </div>
                                                <div class="modla-body pl-3 pt-3" style="color:black;">
                                                    <del>{{ comment | linebreaks }}</del>
                                                </div>
                                                <div class="modal-footer">
                                                    <button type="button" class="btn" style="background-color:rgb(0,62,62);color:white;"data-dismiss="modal">Cancel</button>
                                                    <a role="button" class="btn btn-danger" href="/shoppingmall_main/delete_comment/{{ comment.pk }}/">Delete</a>
                                                </div>
                                                </div>
                                            </div>
                                        </div>
                                        {% endif %}
                                        <div class="fw-bold">{{comment.author.username}}
                                        <small>{{comment.created_at}}</small>
                                        </div>
                                        <p>{{comment.content | linebreaks }}</p>
                                        {% if comment.created_at != comment.modified_at %}
                                            <p class=" float-right" style="color:balck;">
                                                <small >Updated : {{comment.modified_at}}</small>
                                            </p>
                                        {% endif %}
                                    </div>

                                </div>

                                <!--     대댓글 하나하나를 for문으로 분리시켜서 하나씩 뜨게 함 -->
                           {% for recom in comment.recomment_set.all %}
                            <small class="mt-0 " style="color:black">
                                <!-- 대댓글 작성자 / 대댓글 생성 시간 -->
                                <i class="fas fa-reply"> </i> {{ recom.content }} by {{ recom.user }} : {{ recom.created_at}}
                                <br>
                            </small>

                            {% endfor %}

                                <!--     로그인 한 상태에서만 대댓글 클릭 가능 -->
                            {% if request.user.is_authenticated %}
                                <!-- reply comment -->


                            <!-- recomment_Form -->
                            <form id="recomment-form" method="post" action="/shoppingmall_main/recomment/{{comment.pk}}/">
                                {% csrf_token %}
                                {{  subcomment_form | crispy }}
                                <input type="hidden" name="comment" value="{{ subcomment.id }}">
                                <button  type="submit" class="btn btn-sm float-right" style="background-color:rgb(0,62,62);color:snow">
                                    Reply
                                </button>
                            </form> {% endif %}
                               <br>
                                <br>


                                {% endfor %}

                                {% endif %}

                            </div>
                        </div>
                    </div>
</div>

{% endblock %}

shoppingmall_main/templates/shoppingmall_main/shoppingitem_form.html
{% extends 'shoppingmall_main/base.html' %}
{% load crispy_forms_tags %}

{% block head_title %}
    Create ShoppingItem
{% endblock %}

{% block main_area %}
<div class="container mt-3">
    <h1 style="color:rgb(0, 62, 62)">Create ShoppingItem</h1>
    <hr>
    <form method="post" enctype="multipart/form-data" >
        {% csrf_token %}

            {{form | crispy}}
        <div id="div_id_tags_str">
            <label for="id_tags">Tags:</label>
            <input type="text" id="id_tags" name="tags_str" value="{{tags_str_default}}"
            class="textinput textInput form-control">
        </div>

        <button type="submit" class="btn float-right m-3" style="background-color : snow; border: 2px solid rgb(0,62,62);border-radius:50%">Submit</button>
    </form>

    {{ form.media }}
</div>
{% endblock %}

shoppingmall_main/templates/shoppingmall_main/shoppingitem_update_form.html
{% extends 'shoppingmall_main/base.html' %}
{% load crispy_forms_tags %}

{% block head_title %}
    Update ShoppingItem
{% endblock %}

{% block main_area %}
<div class="container mt-3">
    <h1 style="color:rgb(0, 62, 62)">Update ShoppingItem</h1>
    <hr/>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
            {{form | crispy}}
            <div id="div_id_tags_str">
                <label for="id_tags">Tags:</label>
                <input id="id_tags" type="text" name="tags_str" value="{{tags_str_default}}" class="textinput textInput form-control">
            </div>
        <button type="submit" class="btn float-right m-3"style="background-color : snow; border: 2px solid rgb(0,62,62);border-radius:50%">Submit</button>
    </form>

    {{ form.media }}
</div>
{% endblock %}